language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

matrix:
  allow_failures:
    - php: 5.6

services:
  - mongodb

env:
  - MONGO_VERSION=1.5.2
  - MONGO_VERSION=1.4.5
  - MONGO_VERSION=1.3.7

before_script:
  - printf "\n" | pecl install -f mongo-${MONGO_VERSION}
  - composer require satooshi/php-coveralls:dev-master --dev --no-progress --prefer-source
  - phpenv rehash

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls --exclude-no-stmt