language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - MONGO_VERSION=1.4.5
  - MONGO_VERSION=1.3.6

services:
  - mongodb

before_script:
  - printf "\n" | pecl install -f mongo-${MONGO_VERSION}
  - composer --dev --prefer-source install
  - phpenv rehash

script: phpunit